steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - -c
  - |
    mv `find /workspace -maxdepth 1 ! -name go | grep /workspace/` .
    python /builder/google-cloud-sdk/platform/google_appengine/goapp get google.golang.org/appengine
    python /builder/google-cloud-sdk/platform/google_appengine/goapp test github.com/star-integrations/go-appengine-baseurl/baseurl
  dir: '/workspace/go/src/github.com/star-integrations/go-appengine-baseurl'
  env:
    - 'GOPATH=/workspace/go'